# Generated by Django 2.2 on 2020-10-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('num_Mesa', models.AutoField(primary_key=True, serialize=False)),
                ('cantSillas', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('num_Res', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Cliente')),
            ],
        ),
    ]
