# Generated by Django 2.2 on 2020-11-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompaniante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('num_Mesa', models.AutoField(primary_key=True, serialize=False)),
                ('cantSillas', models.IntegerField()),
                ('status', models.CharField(choices=[('LB', 'Libre'), ('RS', 'Reservada'), ('OP', 'Ocupada'), ('NO', 'No Disponible')], default='Libre', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('num_Res', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('num_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('cod_pago', models.AutoField(primary_key=True, serialize=False)),
                ('num_trj', models.CharField(max_length=20)),
                ('fechaV', models.DateField()),
                ('codSeg', models.CharField(max_length=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buffet.Cliente')),
            ],
        ),
    ]
