# Generated by Django 2.2 on 2020-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffet', '0002_acompaniante_bebida_pago_platillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='cantSillas',
            field=models.IntegerField(verbose_name=6),
        ),
    ]
