# Generated by Django 2.2 on 2020-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffet', '0002_auto_20201112_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='cantSillas',
            field=models.IntegerField(),
        ),
    ]
