# Generated by Django 2.2 on 2020-10-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buffet', '0003_auto_20201029_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='cantSillas',
            field=models.CharField(max_length=6),
        ),
    ]
