# Generated by Django 2.2 on 2020-11-26 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buffet', '0006_auto_20201119_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Buffet.Mesa'),
        ),
    ]
